version: '3.8'

services:
  backend:
    build:
      context: ./application_backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./application_frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"   # NGINX is configured to listen on 3000
    depends_on:
      - backend       # Waits for backend to start first
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
